---
# file roles/autoinstall-tevii-firmware/tasks/main.yml

- name: get information about usb and pci hardware and loaded kernel modules
  hardware_facts:
    usb: True
    pci: True
    modules: True
    gpus: True

- name: determine needed firmware files by device ids
  block:
    - name: add firmware for Tevii S460 to variable tevii_firmware_files if a card has been detected
      set_fact:
        tevii_firmware_files: "{{tevii_firmware_files}} + ['dvb-fe-cx24116.fw']"
      when:
        - '"14f1:8800" in pci'
        - '"14f1:8802" in pci'
  when:
    - not tevii_firmware_files

- name: Download firmware for Tevii cards and copy required files to /lib/firmware
  block:
    - name: apt | unrar-free required -> install if not available
      apt:
        name: unrar-free
        state: present
        install_recommends: no

    - name: Create download folder for tevii linux drivers under /tmp/tevii
      file:
        path: /tmp/tevii/
        state: directory
        mode: 0664

    - name: Download Tevii_linuxdriver_0815.rar from tevii.com
      get_url:
        url: http://tevii.com/Tevii_linuxdriver_0815.rar
        dest: /tmp/tevii/Tevii_linuxdriver_0815.rar
        mode: 0664

    - name: Extract drivers
      command: unrar e /tmp/tevii/Tevii_linuxdriver_0815.rar /tmp/tevii/fw/ -o+
      
    - name: Copy firmware drivers
      copy:
        src: "/tmp/tevii/fw/{{item}}"
        dest: /tmp/tevii/
        owner: root
        group: root
        mode: 0644
      with_items: '{{ tevii_firmware_files }}'
      #notify: ['Trigger Udev']

  #  # Remove temporary files
  #   - file:
  #      path: /tmp/tevii
  #      state: absent

  # when:
  #   - tevii_firmware_files is undefined
  #   - tevii_firmware_files is none

  tags:
    - install
    - autodetect
    - tevii
