---
# file roles/autoinstall-tevii-firmware/tasks/main.yml

- name: determine needed firmware files by device ids
  block:
    - name: add firmware for Tevii S460 to variable tevii_firmware_files if a card has been detected
      set_fact:
        tevii_firmware_files: "{{tevii_firmware_files}} + ['dvb-fe-cx24116.fw']"
      with_items: '{{ tevii_cx24116_supported_products }}'
      when:
        - 'item in pci'
  when:
    - not tevii_firmware_files

- name: Download firmware for Tevii cards and copy required files to /lib/firmware
  block:
    - name: apt | unrar-free required -> install if not available
      apt:
        name: unrar-free
        state: present
        install_recommends: no

    - name: Create download folder for tevii linux drivers under /tmp/tevii
      file:
        path: /tmp/tevii/fw
        state: directory
        mode: 0664

    - name: Download Tevii_linuxdriver_0815.rar from tevii.com
      get_url:
        url: http://tevii.com/Tevii_linuxdriver_0815.rar
        dest: /tmp/tevii/Tevii_linuxdriver_0815.rar
        mode: 0664

    - name: Extract drivers
      command: unrar e /tmp/tevii/Tevii_linuxdriver_0815.rar /tmp/tevii/fw/ -o+
      
    - name: Copy firmware drivers
      copy:
        src: "/tmp/tevii/fw/{{item}}"
        dest: /tmp
        owner: root
        group: root
        mode: 0644
      with_items: '{{ tevii_firmware_files }}'
      notify: ['Trigger Udev']

    - name: Remove temporary files
      file:
        path: /tmp/tevii
        state: absent

  when: not(
    (tevii_firmware_files is undefined)
    or
    (tevii_firmware_files is none)
    or
    (tevii_firmware_files | trim == ''))

  tags:
    - install
    - autodetect
    - tevii
